# stylua.toml for Neovim Lua configs
# https://github.com/JohnnyMorganz/StyLua#configuration

# Max line length before wrapping
column_width = 180

# Indentation
indent_type = "Spaces"
indent_width = 4

# Line endings: "Unix" or "Windows"
line_endings = "Unix"

